inherit_gem:
  codestyle:
    - default.yml

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

# TODO: submit a patch to openapi generator
Metrics/CyclomaticComplexity:
  Enabled: false

# TODO: submit a patch to openapi generator
Lint/DuplicateMethods:
  Enabled: false

# TODO: submit a patch to openapi generator
Style/ClassVars:
  Enabled: false

# TODO: submit a patch to openapi generator
Lint/UselessAssignment:
  Enabled: false

# TODO: submit a patch to openapi generator
Lint/UnderscorePrefixedVariableName:
  Enabled: false