# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

$LOAD_PATH.push File.expand_path('lib', __dir__)
require 'yousign_client/version'

Gem::Specification.new do |s|
  s.name = 'yousign_client'
  s.version = YousignClient::VERSION
  s.platform = Gem::Platform::RUBY
  s.authors = ['Thomas Burgaud']
  s.email = ['thomas.burgaud@cashbee.fr']
  s.homepage = 'https://github.com/cashbee-team/yousign_client'
  s.summary = 'Yousign API Documentation Ruby Gem'
  s.description = 'Yousign API Documentation Ruby Gem'
  s.license = 'Apache-2.0'
  s.required_ruby_version = '>= 2.6'

  s.add_runtime_dependency 'typhoeus', '~> 1.4.0'

  s.files = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.test_files = `find spec/*`.split("\n")
  s.executables = []
  s.require_paths = ['lib']
end
