=begin
#Yousign API Swagger

#For your information, the Yousign API documentation is available at https://dev.yousign.com/

OpenAPI spec version: 2.1
Contact: support@yousign.fr
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::CheckDocumentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CheckDocumentsApi' do
  before do
    # run before each test
    @instance = YousignClient::CheckDocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckDocumentsApi' do
    it 'should create an instance of CheckDocumentsApi' do
      expect(@instance).to be_instance_of(YousignClient::CheckDocumentsApi)
    end
  end

  # unit tests for check_document_bank_accounts_id_get
  # Get informations about a bank document (RIB)
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @return [CheckDocumentBankAccountsOutput]
  describe 'check_document_bank_accounts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for check_document_bank_accounts_post
  # Verify a bank document (RIB)
  # @param authorization Authentication credentials for HTTP authentication
  # @param content_type The MIME type of the body of the request
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CheckDocumentBankAccountsOutput]
  describe 'check_document_bank_accounts_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for check_document_identities_id_get
  # Get informations about an identity document (passport, id cards)
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @return [CheckDocumentIdentitiesOutput]
  describe 'check_document_identities_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for check_document_identities_post
  # Verify an identity document (passport, id cards)
  # @param authorization Authentication credentials for HTTP authentication
  # @param content_type The MIME type of the body of the request
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CheckDocumentIdentitiesOutput]
  describe 'check_document_identities_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
