# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::FilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FilesApi' do
  before do
    # run before each test
    @api_instance = YousignClient::FilesApi.new
  end

  describe 'test an instance of FilesApi' do
    it 'creates an instance of FilesApi' do
      expect(@api_instance).to be_instance_of(YousignClient::FilesApi)
    end
  end

  # unit tests for files_id_download_get
  # Download a File
  # Used to get the base64 content of a file
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'files_id_download_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_id_duplicate_post
  # Duplicate a File
  # Duplicate a file. It will be create a clone of this file, with a new ID.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [FileOutput]
  describe 'files_id_duplicate_post test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_id_get
  # Find a File by ID
  # Returns all the information regarding the File but without its content (for performance issue).
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [FileOutput]
  describe 'files_id_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_post
  # Create a new File
  # Used to upload a file in base64 on our platform
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [FileOutput]
  describe 'files_post test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
