# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::OperationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OperationsApi' do
  before do
    # run before each test
    @api_instance = YousignClient::OperationsApi.new
  end

  describe 'test an instance of OperationsApi' do
    it 'creates an instance of OperationsApi' do
      expect(@api_instance).to be_instance_of(YousignClient::OperationsApi)
    end
  end

  # unit tests for operations_id_get
  # Find an Operation by ID
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [OperationOutput]
  describe 'operations_id_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for operations_post
  # Create a new Operation
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [OperationOutput]
  describe 'operations_post test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
