# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::OrganizationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationsApi' do
  before do
    # run before each test
    @api_instance = YousignClient::OrganizationsApi.new
  end

  describe 'test an instance of OrganizationsApi' do
    it 'creates an instance of OrganizationsApi' do
      expect(@api_instance).to be_instance_of(YousignClient::OrganizationsApi)
    end
  end

  # unit tests for organizations_get
  # List all Organizations
  # @param [Hash] opts the optional parameters
  # @return [Array<OrganizationOutput>]
  describe 'organizations_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
