=begin
#Yousign API Swagger

#For your information, the Yousign API documentation is available at https://dev.yousign.com/

OpenAPI spec version: 2.1
Contact: support@yousign.fr
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::ProceduresApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProceduresApi' do
  before do
    # run before each test
    @instance = YousignClient::ProceduresApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProceduresApi' do
    it 'should create an instance of ProceduresApi' do
      expect(@instance).to be_instance_of(YousignClient::ProceduresApi)
    end
  end

  # unit tests for export_procedures_get
  # Export Procedure list
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Return Procedure list based on the status for each Procedure
  # @option opts [String] :name Filter by name (contains)
  # @option opts [String] :members_firstname Filter by member firstname (contains)
  # @option opts [String] :members_lastname Filter by member lastname (contains)
  # @option opts [String] :members_phone Filter by member phone (contains)
  # @option opts [String] :members_email Filter by member email (contains)
  # @option opts [String] :files_name Filter by file name (contains)
  # @option opts [Array<Date>] :created_at Filter by creation date  createdAt[after]&#x3D;2017-09-18 createdAt[before]&#x3D;2017-09-18 createdAt[strictly_after]&#x3D;2017-09-18 createdAt[strictly_before]&#x3D;2017-09-18
  # @option opts [Array<Date>] :updated_at Filter by update date  updatedAt[after]&#x3D;2017-09-18 updatedAt[before]&#x3D;2017-09-18 updatedAt[strictly_after]&#x3D;2017-09-18 updatedAt[strictly_before]&#x3D;2017-09-18
  # @option opts [Array<Date>] :expires_at Filter by expire date  expiresAt[after]&#x3D;2017-09-18 expiresAt[before]&#x3D;2017-09-18 expiresAt[strictly_after]&#x3D;2017-09-18 expiresAt[strictly_before]&#x3D;2017-09-18
  # @option opts [Array<Date>] :deleted_at Filter by delete date  deletedAt[after]&#x3D;2017-09-18 deletedAt[before]&#x3D;2017-09-18 deletedAt[strictly_after]&#x3D;2017-09-18 deletedAt[strictly_before]&#x3D;2017-09-18
  # @option opts [String] :order_created_at Order by attribut
  # @return [String]
  describe 'export_procedures_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_get
  # Get Procedure list
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Return Procedure list based on the status for each Procedure
  # @option opts [BOOLEAN] :template Used to get Procedure template list
  # @option opts [Array<String>] :members Get Procedure list for given members (paraph mode)
  # @option opts [String] :items_per_page Number of items per page for the pagination
  # @option opts [BOOLEAN] :pagination Enable the pagination
  # @option opts [Integer] :page Page of the pagination
  # @option opts [String] :name Filter by name (contains)
  # @option opts [String] :members_firstname Filter by member firstname (contains)
  # @option opts [String] :members_lastname Filter by member lastname (contains)
  # @option opts [String] :members_phone Filter by member phone (contains)
  # @option opts [String] :members_email Filter by member email (contains)
  # @option opts [String] :files_name Filter by file name (contains)
  # @option opts [Array<Date>] :created_at Filter by creation date  createdAt[after]&#x3D;2017-09-18 createdAt[before]&#x3D;2017-09-18 createdAt[strictly_after]&#x3D;2017-09-18 createdAt[strictly_before]&#x3D;2017-09-18
  # @option opts [Array<Date>] :updated_at Filter by update date  updatedAt[after]&#x3D;2017-09-18 updatedAt[before]&#x3D;2017-09-18 updatedAt[strictly_after]&#x3D;2017-09-18 updatedAt[strictly_before]&#x3D;2017-09-18
  # @option opts [Array<Date>] :expires_at Filter by expire date  expiresAt[after]&#x3D;2017-09-18 expiresAt[before]&#x3D;2017-09-18 expiresAt[strictly_after]&#x3D;2017-09-18 expiresAt[strictly_before]&#x3D;2017-09-18
  # @option opts [Array<Date>] :deleted_at Filter by delete date  deletedAt[after]&#x3D;2017-09-18 deletedAt[before]&#x3D;2017-09-18 deletedAt[strictly_after]&#x3D;2017-09-18 deletedAt[strictly_before]&#x3D;2017-09-18
  # @option opts [String] :order_created_at Order by createdAt  order[createdAt]&#x3D;asc order[createdAt]&#x3D;desc
  # @return [Array<ProcedureOutput>]
  describe 'procedures_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_id_delete
  # Delete a Procedure
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'procedures_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_id_duplicate_post
  # Duplicate a Procedure
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param content_type The MIME type of the body of the request
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProcedureOutput]
  describe 'procedures_id_duplicate_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_id_get
  # Find a Procedure by ID
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @return [ProcedureOutput]
  describe 'procedures_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_id_proof_get
  # Get a Procedure proof file
  # Get a Procedure proof file
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'procedures_id_proof_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_id_put
  # Update a Procedure
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param content_type The MIME type of the body of the request
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProcedureOutput]
  describe 'procedures_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_id_remind_post
  # Remind a Procedure
  # @param id 
  # @param authorization Authentication credentials for HTTP authentication
  # @param content_type The MIME type of the body of the request
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProcedureOutput]
  describe 'procedures_id_remind_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procedures_post
  # Create a new Procedure
  # @param authorization Authentication credentials for HTTP authentication
  # @param content_type The MIME type of the body of the request
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProcedureOutput]
  describe 'procedures_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
