# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::ServerStampsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServerStampsApi' do
  before do
    # run before each test
    @api_instance = YousignClient::ServerStampsApi.new
  end

  describe 'test an instance of ServerStampsApi' do
    it 'creates an instance of ServerStampsApi' do
      expect(@api_instance).to be_instance_of(YousignClient::ServerStampsApi)
    end
  end

  # unit tests for server_stamps_id_get
  # Find a Server Stamp by ID
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [ServerStampOutput]
  describe 'server_stamps_id_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for server_stamps_post
  # Create a Server Stamp
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [ServerStampOutput]
  describe 'server_stamps_post test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
