=begin
#Yousign API Swagger

#For your information, the Yousign API documentation is available at https://dev.yousign.com/

OpenAPI spec version: 2.1
Contact: support@yousign.fr
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::UserGroupsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserGroupsApi' do
  before do
    # run before each test
    @instance = YousignClient::UserGroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserGroupsApi' do
    it 'should create an instance of UserGroupsApi' do
      expect(@instance).to be_instance_of(YousignClient::UserGroupsApi)
    end
  end

  # unit tests for user_groups_get
  # Get User Group list
  # @param [Hash] opts the optional parameters
  # @return [Array<UserGroup>]
  describe 'user_groups_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for user_groups_id_get
  # Find a User Group by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [UserGroup]
  describe 'user_groups_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
