# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::UserGroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserGroupsApi' do
  before do
    # run before each test
    @api_instance = YousignClient::UserGroupsApi.new
  end

  describe 'test an instance of UserGroupsApi' do
    it 'creates an instance of UserGroupsApi' do
      expect(@api_instance).to be_instance_of(YousignClient::UserGroupsApi)
    end
  end

  # unit tests for user_groups_get
  # Get User Group list
  # @param [Hash] opts the optional parameters
  # @return [Array<UserGroup>]
  describe 'user_groups_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for user_groups_id_get
  # Find a User Group by ID
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [UserGroup]
  describe 'user_groups_id_get test' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
