# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YousignClient::SignatureUiOutputRedirectSuccess
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe YousignClient::SignatureUiOutputRedirectSuccess do
  let(:instance) { YousignClient::SignatureUiOutputRedirectSuccess.new }

  describe 'test an instance of SignatureUiOutputRedirectSuccess' do
    it 'creates an instance of SignatureUiOutputRedirectSuccess' do
      expect(instance).to be_instance_of(YousignClient::SignatureUiOutputRedirectSuccess)
    end
  end

  describe 'test attribute "url"' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "target"' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["_top", "_blank", "_parent", "_self"])
      # validator.allowable_values.each do |value|
      #   expect { instance.target = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "auto"' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
