# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YousignClient::WorkspaceConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe YousignClient::WorkspaceConfig do
  let(:instance) { YousignClient::WorkspaceConfig.new }

  describe 'test an instance of WorkspaceConfig' do
    it 'creates an instance of WorkspaceConfig' do
      expect(instance).to be_instance_of(YousignClient::WorkspaceConfig)
    end
  end

  describe 'test attribute "authentication_modes"' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["sms", "inwebo"])
      # validator.allowable_values.each do |value|
      #   expect { instance.authentication_modes = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "procedure"' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "email"' do
    it 'works' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
