# frozen_string_literal: true

# #Yousign API Swagger
#
# For your information, the Yousign API documentation is available at https://dev.yousign.com/
#
# The version of the OpenAPI document: 2.1
# Contact: support@yousign.fr
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.4.0
#

require 'date'
require 'time'

module YousignClient
  class MemberInput
    # ID of the user in your companies. Informations about the member will be duplicate (first name, last name, email and phone number).  Required if none of fields above are specified.
    attr_accessor :user

    # Type of a member. \"signer\" to sign documents (legally) and \"validator\" to validate documents.
    attr_accessor :type

    # Firstname of an external member. Required if user field is blank
    attr_accessor :firstname

    # Lastname of an external member. Required if user field is blank
    attr_accessor :lastname

    # Email of an external member. Required if user field is blank
    attr_accessor :email

    # Phone of an external member. Required if user field is blank
    attr_accessor :phone

    # If the procedure have the boolean \"ordered\" at true, you can define position of the order to invite your members to sign. Only the first member will be invited to sign.  When the first member have signed, the second will be invited, etc...
    attr_accessor :position

    attr_accessor :file_objects, :operation_level, :operation_custom_modes, :mode_sms_configuration

    # Procedure id reference
    attr_accessor :procedure

    class EnumAttributeValidator
      attr_reader :datatype, :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        user                   => user,
        type                   => type,
        firstname              => firstname,
        lastname               => lastname,
        email                  => email,
        phone                  => phone,
        position               => position,
        file_objects           => :fileObjects,
        procedure              => procedure,
        operation_level        => :operationLevel,
        operation_custom_modes => :operationCustomModes,
        mode_sms_configuration => :modeSmsConfiguration
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        user                   => :String,
        type                   => :String,
        firstname              => :String,
        lastname               => :String,
        email                  => :String,
        phone                  => :String,
        position               => :Integer,
        file_objects           => :'Array<FileObjectInput>',
        procedure              => :String,
        operation_level        => :String,
        operation_custom_modes => :'Array<String>',
        mode_sms_configuration => :ModeSmsConfiguration
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = { })
      unless attributes.is_a?(Hash)
        raise ArgumentError, 'The input argument (attributes) must be a hash in `YousignClient::MemberInput` initialize method'
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({ }) do |(k, v), h|
        unless self.class.attribute_map.key?(k.to_sym)
          raise ArgumentError, "`#{k}` is not a valid attribute in `YousignClient::MemberInput`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end

        h[k.to_sym] = v
      end

      if attributes.key?(:user)
        self.user = attributes[:user]
      end

      self.type = if attributes.key?(:type)
                    attributes[:type]
                  else
                    'signer'
        end

      if attributes.key?(:firstname)
        self.firstname = attributes[:firstname]
      end

      if attributes.key?(:lastname)
        self.lastname = attributes[:lastname]
      end

      if attributes.key?(:email)
        self.email = attributes[:email]
      end

      if attributes.key?(:phone)
        self.phone = attributes[:phone]
      end

      if attributes.key?(:position)
        self.position = attributes[:position]
      end

      if attributes.key?(:file_objects)
        if (value = attributes[:file_objects]).is_a?(Array)
          self.file_objects = value
        end
      end

      if attributes.key?(:procedure)
        self.procedure = attributes[:procedure]
      end

      if attributes.key?(:operation_level)
        self.operation_level = attributes[:operation_level]
      end

      if attributes.key?(:operation_custom_modes)
        if (value = attributes[:operation_custom_modes]).is_a?(Array)
          self.operation_custom_modes = value
        end
      end

      if attributes.key?(:mode_sms_configuration)
        self.mode_sms_configuration = attributes[:mode_sms_configuration]
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      []
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      type_validator = EnumAttributeValidator.new('String', %w[signer validator])
      return false unless type_validator.valid?(@type)

      operation_level_validator = EnumAttributeValidator.new('String', %w[none custom advanced])
      return false unless operation_level_validator.valid?(@operation_level)

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', %w[signer validator])
      unless validator.valid?(type)
        raise ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end

      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operation_level Object to be assigned
    def operation_level=(operation_level)
      validator = EnumAttributeValidator.new('String', %w[none custom advanced])
      unless validator.valid?(operation_level)
        raise ArgumentError, "invalid value for \"operation_level\", must be one of #{validator.allowable_values}."
      end

      @operation_level = operation_level
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        user == other.user &&
        type == other.type &&
        firstname == other.firstname &&
        lastname == other.lastname &&
        email == other.email &&
        phone == other.phone &&
        position == other.position &&
        file_objects == other.file_objects &&
        procedure == other.procedure &&
        operation_level == other.operation_level &&
        operation_custom_modes == other.operation_custom_modes &&
        mode_sms_configuration == other.mode_sms_configuration
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [user, type, firstname, lastname, email, phone, position, file_objects, procedure, operation_level, operation_custom_modes, mode_sms_configuration].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize(Regexp.last_match(1), v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        { }.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = YousignClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = { }
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        { }.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
